const START='2026-10-08', END='2026-12-20', STORAGE_KEY='university-os-completed-pages';
const subjects={psicologia:{name:'Psicologia della Comunicazione',short:'Psicologia',cfu:12,color:'#7865d4',target:75,minPerPage:[2.5,4]},linguistica:{name:'Linguistica e Comunicazione',short:'Linguistica',cfu:12,color:'#2f6bf2',target:150,minPerPage:[3,4.67]},persuasione:{name:'Comunicazione e Persuasione',short:'Persuasione',cfu:12,color:'#d8892d',target:135,minPerPage:[2.5,4]},storia:{name:'Istituzioni di Storia Contemporanea',short:'Storia',cfu:12,color:'#2b9d6f',target:315,minPerPage:[3,4]}};
const classes={1:[['08:00–11:00','Processi, Soggetti e Poteri'],['11:00–14:00','Comunicazione e Persuasione']],2:[['08:00–11:00','Linguistica e Comunicazione'],['11:00–14:00','Istituzioni di Storia Contemporanea'],['14:00–17:00','Comunicazione e Persuasione']],3:[['08:00–11:00','Linguistica e Comunicazione / Psicologia della Comunicazione'],['11:00–14:00','Istituzioni di Storia Contemporanea'],['17:00–20:00','Critical Thinking']],4:[['11:00–14:00','Critical Thinking'],['17:00–20:00','Processi, Soggetti e Poteri']],5:[['14:00–17:00','Laboratorio di Giornalismo Televisivo']]};
const study={1:[['psicologia',10],['persuasione',10]],2:[],3:[['storia',20],['psicologia',5]],4:[['storia',30],['linguistica',15],['psicologia',10]],5:[['storia',30],['linguistica',15],['persuasione',15]],6:[['storia',35],['linguistica',20],['persuasione',20]],0:[]};
const dayProfiles={1:'Giornata leggera',2:'Solo lezioni',3:'Giornata leggera',4:'Giornata pesante',5:'Giornata pesante',6:'Giornata pesante',0:'Riposo'};
const iso=d=>d.toISOString().slice(0,10);
const dateAt=(y,m,d)=>new Date(y,m,d,12);
const todayDate=new Date();
const TODAY=iso(todayDate);
let view=new Date(todayDate.getFullYear(),todayDate.getMonth(),1), calendarMode='month';
let completed=new Set();
const active=d=>iso(d)>=START&&iso(d)<=END;
const weekday=d=>(d.getDay()+6)%7+1;
const dataFor=d=>{const key=iso(d),day=weekday(d),isStudyDay=key>=START&&key<=END;return{key,classes:classes[day]||[],study:isStudyDay?(study[day]||[]).map(([subject,pages])=>({subject,pages,done:completed.has(`${key}:${subject}`)})):[]}};
const estimateForTask=task=>{const [low,high]=subjects[task.subject].minPerPage;return[Math.round(task.pages*low),Math.round(task.pages*high)]};
const estimateForDay=tasks=>tasks.reduce(([low,high],task)=>{const estimate=estimateForTask(task);return[low+estimate[0],high+estimate[1]]},[0,0]);
const monthDays=()=>{const y=view.getFullYear(),m=view.getMonth(),first=dateAt(y,m,1),start=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),out=[];for(let i=0;i<start;i++)out.push(null);for(let d=1;d<=days;d++)out.push(dateAt(y,m,d));while(out.length%7)out.push(null);return out};
const totals=()=>{let pages=0,done=0,tasks=0,doneTasks=0;for(let d=dateAt(2026,9,8);d<=dateAt(2026,11,20);d.setDate(d.getDate()+1)){if(!active(d))continue;dataFor(d).study.forEach(t=>{pages+=t.pages;tasks++;if(t.done){done+=t.pages;doneTasks++}})}return{pages,done,tasks,doneTasks}};
const subjectTotals=()=>{const result=Object.fromEntries(Object.keys(subjects).map(key=>[key,{pages:0,done:0}]));for(let d=dateAt(2026,9,8);d<=dateAt(2026,11,20);d.setDate(d.getDate()+1)){dataFor(d).study.forEach(task=>{result[task.subject].pages+=task.pages;if(task.done)result[task.subject].done+=task.pages})}return result};
function renderToday(){const x=dataFor(todayDate),t=totals(),totalPages=x.study.reduce((sum,task)=>sum+task.pages,0),donePages=x.study.filter(task=>task.done).reduce((sum,task)=>sum+task.pages,0),pagePct=Math.round(donePages/totalPages*100)||0,estimate=estimateForDay(x.study);document.querySelector('#todayDateLabel').textContent=todayDate.toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long'}).toUpperCase();document.querySelector('#todayLessons').innerHTML=x.classes.map(c=>`<div class="lesson-item"><span class="time">${c[0]}</span><i class="lesson-bar"></i><div><strong>${c[1]}</strong><small>Lezione in aula</small></div></div>`).join('');document.querySelector('#todayTasks').innerHTML=x.study.map(task=>{const taskEstimate=estimateForTask(task);return`<button class="task-item ${task.done?'is-done':''}" data-task="${task.subject}" aria-pressed="${task.done}"><span class="task-check">${task.done?'✓':''}</span><span class="task-copy"><strong>${subjects[task.subject].short}</strong><small>${task.done?task.pages:0} / ${task.pages} pagine completate · ${taskEstimate[0]}–${taskEstimate[1]} min</small></span><span class="page-count">${task.pages}<small>pagine</small></span></button>`}).join('');document.querySelector('#taskCount').textContent=`${donePages}/${totalPages} p`;document.querySelector('#todayStudySummary').textContent=totalPages?`${dayProfiles[weekday(todayDate)]} · ${totalPages} pagine · ${estimate[0]}–${estimate[1]} min`:'Solo lezioni · nessuna pagina';document.querySelector('#todayProgress').textContent=`${pagePct}%`;document.querySelector('.progress-dial').style.background=`conic-gradient(var(--blue) ${pagePct}%,rgba(47,107,242,.12) 0)`;document.querySelectorAll('.task-item').forEach(item=>item.onclick=()=>toggleTask(TODAY,item.dataset.task));return t}
function renderYesterday(){const yesterday=new Date(todayDate);yesterday.setDate(yesterday.getDate()-1);const x=dataFor(yesterday),totalPages=x.study.reduce((sum,task)=>sum+task.pages,0),donePages=x.study.filter(task=>task.done).reduce((sum,task)=>sum+task.pages,0),label=yesterday.toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long'});document.querySelector('#yesterdaySummary').textContent=totalPages?`${label} · ${donePages} di ${totalPages} pagine completate`:`${label} · nessuna pagina assegnata`;document.querySelector('#yesterdayCount').textContent=`${donePages}/${totalPages} p`;document.querySelector('#yesterdayTasks').innerHTML=x.study.length?x.study.map(task=>{const taskEstimate=estimateForTask(task);return`<button class="task-item ${task.done?'is-done':''}" data-yesterday-task="${task.subject}" aria-pressed="${task.done}"><span class="task-check">${task.done?'✓':''}</span><span class="task-copy"><strong>${subjects[task.subject].short}</strong><small>${task.done?task.pages:0} / ${task.pages} pagine completate · ${taskEstimate[0]}–${taskEstimate[1]} min</small></span><span class="page-count">${task.pages}<small>pagine</small></span></button>`}).join(''):`<p class="empty-state">Nessuna pagina da verificare.</p>`;document.querySelectorAll('[data-yesterday-task]').forEach(item=>item.onclick=()=>toggleTask(iso(yesterday),item.dataset.yesterdayTask))}
const renderTodayWithYesterday=renderToday;
renderToday=()=>{const result=renderTodayWithYesterday();renderYesterday();return result};
function renderCalendar(){const title=view.toLocaleDateString('it-IT',{month:'long',year:'numeric'}).replace(/^./,c=>c.toUpperCase());document.querySelector('#monthTitle').textContent=title;const content=document.querySelector('#calendarContent');if(calendarMode==='week'){const start=new Date(todayDate);start.setDate(todayDate.getDate()-((todayDate.getDay()+6)%7));content.innerHTML=`<div class="week-list">${Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const x=dataFor(d),today=iso(d)===TODAY,totalPages=x.study.reduce((sum,task)=>sum+task.pages,0),donePages=x.study.filter(task=>task.done).reduce((sum,task)=>sum+task.pages,0),estimate=estimateForDay(x.study);return`<div class="week-day ${today?'current':''}"><div><strong>${d.toLocaleDateString('it-IT',{weekday:'short',day:'numeric'})}</strong><small>${today?'Oggi':dayProfiles[weekday(d)]}</small></div><div><strong>${totalPages} pagine</strong><small>${donePages} completate · ${totalPages?`${estimate[0]}–${estimate[1]} min`:'Nessuna pagina'} · ${x.classes.length} lezioni</small></div><b>${donePages}/${totalPages}p</b></div>`}).join('')}</div>`;return}const weekdays=['Lun','Mar','Mer','Gio','Ven','Sab','Dom'];content.innerHTML=`<div class="calendar-weekdays">${weekdays.map(d=>`<span>${d}</span>`).join('')}</div><div class="calendar-grid">${monthDays().map(d=>{if(!d)return'<div></div>';const x=dataFor(d),key=iso(d),current=key===TODAY;return`<button class="calendar-cell ${current?'current':''} ${!active(d)?'outside':''}" data-date="${key}"><span class="day-number">${d.getDate()}</span>${x.classes.slice(0,1).map(c=>`<div class="calendar-event lesson">${c[0]}</div>`).join('')}${x.study.slice(0,2).map(t=>`<div class="calendar-event study">${subjects[t.subject].short} · ${t.pages}p${t.done?' ✓':''}</div>`).join('')}</button>`}).join('')}</div>`;document.querySelectorAll('.calendar-cell[data-date]').forEach(b=>b.onclick=()=>{b.classList.toggle('selected');const dayData=dataFor(new Date(`${b.dataset.date}T12:00:00`)),totalPages=dayData.study.reduce((sum,task)=>sum+task.pages,0);showToast(`${b.dataset.date===TODAY?'Oggi':'Giorno selezionato'} · ${totalPages} pagine`)})}
function renderExams(){const subjectData=subjectTotals(),totalPages=Object.values(subjectData).reduce((sum,item)=>sum+item.pages,0),completedPages=Object.values(subjectData).reduce((sum,item)=>sum+item.done,0),overallPct=Math.round(completedPages/totalPages*100)||0;document.querySelector('#examOverallPct').textContent=`${overallPct}%`;document.querySelector('#examTotalPages').textContent=`${completedPages}/${totalPages}`;document.querySelector('#examOverallProgress').style.width=`${overallPct}%`;document.querySelector('#examList').innerHTML=Object.entries(subjects).map(([key,s])=>{const item=subjectData[key],pct=Math.round(item.done/item.pages*100)||0;return`<article class="exam-card"><div class="exam-top"><div><h3>${s.name}</h3><span class="exam-subject-state">${pct?'In preparazione':'Da iniziare'}</span></div><span class="exam-pct">${pct}%</span></div><p class="exam-meta">${s.cfu} CFU · ${item.done}/${item.pages} pagine completate</p><div class="progress"><span style="width:${pct}%;background:${s.color}"></span></div></article>`}).join('')}
function toggleTask(key,subject){const id=`${key}:${subject}`;completed.has(id)?completed.delete(id):completed.add(id);localStorage.setItem(STORAGE_KEY,JSON.stringify([...completed]));renderToday();renderCalendar();renderExams();showToast(completed.has(id)?'Pagine completate · progresso aggiornato ✓':'Pagine riaperte · progresso aggiornato')}
function showToast(text){const toast=document.querySelector('#toast');toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1700)}
function switchTab(tab){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('is-active',b.dataset.tab===tab));document.querySelectorAll('.app-view').forEach(v=>v.classList.toggle('is-active',v.dataset.view===tab));if(tab==='calendar')renderCalendar()}
document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>switchTab(button.dataset.tab));
document.querySelectorAll('[data-calendar-view]').forEach(button=>button.onclick=()=>{calendarMode=button.dataset.calendarView;document.querySelectorAll('[data-calendar-view]').forEach(b=>b.classList.toggle('is-selected',b===button));renderCalendar()});
document.querySelector('#prevMonth').onclick=()=>{view.setMonth(view.getMonth()-1);renderCalendar()};
document.querySelector('#nextMonth').onclick=()=>{view.setMonth(view.getMonth()+1);renderCalendar()};
document.querySelector('#calendarToday').onclick=()=>{view=new Date(todayDate.getFullYear(),todayDate.getMonth(),1);calendarMode='month';document.querySelectorAll('[data-calendar-view]').forEach(b=>b.classList.toggle('is-selected',b.dataset.calendarView==='month'));renderCalendar()};
try{completed=new Set(JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]'))}catch(error){console.warn('Impossibile leggere il salvataggio locale delle pagine completate.',error)}
renderToday();renderCalendar();renderExams();
