const START='2026-10-08', END='2026-12-20', TODAY='2026-10-08';
const subjects={
  psicologia:{name:'Psicologia della Comunicazione',short:'Psicologia',cfu:12,color:'#8068d8',planned:0,completed:0,target:75},
  linguistica:{name:'Linguistica e Comunicazione',short:'Linguistica',cfu:12,color:'#4b7cf0',planned:0,completed:0,target:150},
  persuasione:{name:'Comunicazione e Persuasione',short:'Persuasione',cfu:12,color:'#d99932',planned:0,completed:0,target:135},
  storia:{name:'Istituzioni di Storia Contemporanea',short:'Storia',cfu:12,color:'#35a875',planned:0,completed:0,target:315},
  inglese:{name:'Inglese B1',short:'Inglese B1',cfu:null,planned:0,completed:0,target:null}
};
const classOnly=new Set(['Critical Thinking','Processi, Soggetti e Poteri','Laboratorio di Giornalismo Televisivo']);
const classes={1:[['08:00–11:00','Processi, Soggetti e Poteri'],['11:00–14:00','Comunicazione e Persuasione']],2:[['08:00–11:00','Linguistica e Comunicazione'],['11:00–14:00','Istituzioni di Storia Contemporanea'],['14:00–17:00','Comunicazione e Persuasione']],3:[['08:00–11:00','Linguistica e Comunicazione / Psicologia della Comunicazione'],['11:00–14:00','Istituzioni di Storia Contemporanea'],['17:00–20:00','Critical Thinking']],4:[['11:00–14:00','Critical Thinking'],['17:00–20:00','Processi, Soggetti e Poteri']],5:[['14:00–17:00','Laboratorio di Giornalismo Televisivo']]};
const study={1:[['psicologia',10],['persuasione',10]],2:[],3:[['storia',20],['psicologia',5]],4:[['storia',30],['linguistica',15],['psicologia',10]],5:[['storia',30],['linguistica',15],['persuasione',15]],6:[['storia',35],['linguistica',20],['persuasione',20]],0:[]};
let view=new Date('2026-10-01T12:00:00'), expanded=null; const completed=new Set(['2026-10-08:linguistica']);
const iso=d=>d.toISOString().slice(0,10); const dateAt=(y,m,d)=>new Date(y,m,d,12); const active=d=>iso(d)>=START&&iso(d)<=END; const fmt=d=>d.toLocaleDateString('it-IT',{day:'numeric',month:'short'}); const weekday=d=>(d.getDay()+6)%7+1;
function dataFor(d){const key=iso(d), day=weekday(d);return {key,classes:classes[day]||[],study:(study[day]||[]).map(([subject,pages])=>({subject,pages,done:completed.has(`${key}:${subject}`)}))}}
function monthDays(){const y=view.getFullYear(),m=view.getMonth(),first=dateAt(y,m,1),start=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),out=[];for(let i=0;i<start;i++)out.push(null);for(let d=1;d<=days;d++)out.push(dateAt(y,m,d));while(out.length%7)out.push(null);return out}
function totals(){let pages=0,done=0,taskCount=0,doneTasks=0;for(let d=dateAt(2026,9,8);d<=dateAt(2026,11,20);d.setDate(d.getDate()+1)){if(!active(d))continue;dataFor(d).study.forEach(t=>{pages+=t.pages;taskCount++;if(t.done){done+=t.pages;doneTasks++}})}return {pages,done,taskCount,doneTasks}}
function renderSummary(){const t=totals(),pct=Math.round(t.done/t.pages*100)||0;document.querySelector('#summaryStats').innerHTML=[['Overall progress',`${pct}%`,'session completion',pct],['Studio pianificato',`${t.pages} pagine`,'4 esami page-tracked',null],['Completato',`${t.done} pagine`,`${t.doneTasks} task completati`,null],['Lezioni questa settimana','27 ore','3 / 3 frequentate',null]].map(x=>`<article class="stat-card"><div class="stat-label">${x[0]}</div><div class="stat-value">${x[1]}</div><div class="stat-note">${x[2]}</div>${x[3]!==null?`<div class="progress"><span style="width:${x[3]}%"></span></div>`:''}</article>`).join('');const recovery=t.pages-t.done;const b=document.querySelector('#recoveryBanner');b.style.display=recovery?'block':'none';b.innerHTML=`⚠ <strong>Recovery mode</strong> · ${recovery} pagine ancora da completare. Suggerimento: distribuisci il carico sui prossimi giorni disponibili.`}
function renderCalendar(){document.querySelector('#monthTitle').textContent=view.toLocaleDateString('it-IT',{month:'long',year:'numeric'}).replace(/^./,c=>c.toUpperCase());document.querySelector('#calendarGrid').innerHTML=monthDays().map(d=>{if(!d)return '<div></div>';const x=dataFor(d),key=x.key,isCurrent=key===TODAY,isOut=!active(d),completedCount=x.study.filter(t=>t.done).length;return `<button class="day ${isOut?'outside ':''}${isCurrent?'current':''}" data-date="${key}"><div class="day-number">${d.getDate()}</div>${isCurrent?'<span class="day-tag">OGGI</span>':''}${x.classes.slice(0,3).map(c=>`<div class="event class">🏫 ${c[0]} ${c[1]}</div>`).join('')}${x.study.map(t=>`<div class="event study ${t.done?'done':''}">📚 ${subjects[t.subject].short} · ${t.pages}p ${t.done?'✓':''}</div>`).join('')}${x.study.length?`<div class="day-progress">${completedCount}/${x.study.length} task completati</div>`:''}</button>`}).join('');document.querySelectorAll('.day[data-date]').forEach(b=>b.onclick=()=>openDay(b.dataset.date))}
function openDay(key){expanded=key;const d=new Date(`${key}T12:00:00`),x=dataFor(d),item=document.querySelector(`.day[data-date="${key}"]`);document.querySelectorAll('.day').forEach(e=>e.classList.remove('selected'));item?.classList.add('selected');showToast(`${fmt(d)} · ${x.classes.length} lezioni · ${x.study.length} task di studio`);renderTimeline(key)}
function renderWeek(){const t=totals();document.querySelector('#weekOverview').innerHTML=`<div class="week-row"><span>🏫 Lezioni</span><strong>27 ore</strong></div><div class="week-row"><span>📚 Pagine pianificate</span><strong>235</strong></div><div class="week-row"><span>✅ Completato</span><strong>${t.done} pagine</strong></div><div class="week-row"><span>⚠ Rimanente</span><strong>${t.pages-t.done} pagine</strong></div>`}
function renderExams(){document.querySelector('#examList').innerHTML=Object.entries(subjects).map(([key,s])=>{const pct=key==='inglese'?0:Math.min(100,Math.round((key==='psicologia'?20:key==='storia'?10:0)/(key==='psicologia'?50:key==='linguistica'?100:key==='persuasione'?90:200)*100));return `<div class="exam-card"><div class="exam-top"><span class="exam-name">${s.name}</span><span class="exam-pct">${pct}%</span></div><div class="exam-meta">${s.cfu?`${s.cfu} CFU · `:'Solo dashboard'}${key==='inglese'?'Nessun task pagine':'Progress readiness'}</div><div class="progress"><span style="width:${pct}%;background:${s.color}"></span></div></div>`}).join('')}
function renderTimeline(selected=TODAY){const days=[];for(let d=dateAt(2026,9,8);d<=dateAt(2026,11,20);d.setDate(d.getDate()+1))days.push(new Date(d));document.querySelector('#timeline').innerHTML=days.slice(0,14).map(d=>{const x=dataFor(d),key=x.key,done=x.study.length&&x.study.every(t=>t.done),isToday=key===TODAY;return `<article class="timeline-item ${key===selected?'open':''}" data-key="${key}"><div class="timeline-date">${d.toLocaleDateString('it-IT',{weekday:'short',day:'numeric'})}<span>${isToday?'Oggi':active(d)?'Roadmap attiva':'Fuori roadmap'}</span></div><div class="timeline-content"><div class="timeline-title">${isToday?'🔵 ':done?'✅ ':'⬜ '}${x.classes.length} lezioni · ${x.study.reduce((a,t)=>a+t.pages,0)} pagine</div><div class="timeline-summary">${x.study.map(t=>`${subjects[t.subject].short} ${t.pages}p ${t.done?'✓':'○'}`).join(' · ')||'Nessuno studio programmato'}</div><div class="timeline-details"><div class="detail-title">LEZIONI</div>${x.classes.map(c=>`<div class="detail-row"><span>🏫 ${c[1]}</span><span>${c[0]}</span></div>`).join('')||'<span>Nessuna lezione</span>'}<div class="detail-title">STUDIO</div>${x.study.map(t=>`<div class="detail-row"><span>📚 ${subjects[t.subject].name}</span><button onclick="toggleTask('${key}','${t.subject}')">${t.done?'✅':'○'} ${t.pages} pagine</button></div>`).join('')||'<span>Nessun task</span>'}<div class="detail-title">PROGRESS</div><div class="detail-row"><span>Classi frequentate</span><strong>${x.classes.length}/${x.classes.length}</strong></div><div class="detail-row"><span>Studio completato</span><strong>${x.study.filter(t=>t.done).length}/${x.study.length}</strong></div></div></div></article>`}).join('');document.querySelectorAll('.timeline-item').forEach(e=>e.onclick=ev=>{if(ev.target.tagName==='BUTTON')return;e.classList.toggle('open')})}
function toggleTask(key,subject){const id=`${key}:${subject}`;completed.has(id)?completed.delete(id):completed.add(id);renderAll();renderTimeline(key);showToast(completed.has(id)?'Task completato ✓':'Task riaperto')}
function renderCheckpoints(){document.querySelector('#checkpoints').innerHTML=Object.entries(subjects).filter(([k,s])=>s.target).map(([k,s])=>`<div class="check-row"><div class="check-top"><strong>${s.short}</strong><span>0 / ${s.target} pagine</span></div><div class="progress"><span style="width:0%;background:${s.color}"></span></div></div>`).join('')}
function showToast(text){const t=document.querySelector('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function renderAll(){renderSummary();renderCalendar();renderWeek();renderExams();renderCheckpoints();renderTimeline(expanded||TODAY)}
document.querySelector('#prevMonth').onclick=()=>{view.setMonth(view.getMonth()-1);renderCalendar()};document.querySelector('#nextMonth').onclick=()=>{view.setMonth(view.getMonth()+1);renderCalendar()};document.querySelector('#todayButton').onclick=()=>{view=new Date('2026-10-01T12:00:00');renderAll();document.querySelector('#todayButton').focus()};renderAll();
